version: '2'

services:
  scrapper:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.development
    command: ./bin/docker_entrypoint.sh pipenv shell
    ports:
      - "6800:6800"
    volumes:
      - .:/app